# Generated by Django 3.2.3 on 2021-05-25 16:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=256)),
                ('property_description', models.CharField(max_length=1024)),
                ('property_about', models.TextField()),
                ('property_location', models.CharField(max_length=128)),
                ('property_price', models.CharField(max_length=64)),
                ('property_condition', models.CharField(choices=[('New', 'New'), ('Renovated', 'Renovated'), ('Old', 'Old')], max_length=64)),
                ('property_status', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale'), ('Sold Out', 'Sold Out')], max_length=64)),
                ('property_square_meters', models.CharField(max_length=64)),
                ('property_posted_by', models.CharField(choices=[('Property Owner', 'Property Owner'), ('Property Agent', 'Property Agent'), ('Property Manager', 'Property Manager')], max_length=64)),
                ('property_post_date', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 16, 58, 10, 933644, tzinfo=utc))),
                ('property_type', models.CharField(choices=[('Land', 'Land'), ('Plot', 'Plot'), ('Mansion', 'Mansion'), ('Bungalow', 'Bungalow'), ('Cottage', 'Cottage'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('Villa', 'Villa')], max_length=64)),
                ('kitchen', models.BooleanField()),
                ('air_condition', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('cctv', models.BooleanField()),
                ('playground', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
