# Generated by Django 3.2.3 on 2021-08-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.extras


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs_headline', models.CharField(blank=True, max_length=256, null=True)),
                ('faqs_point1', models.TextField(blank=True, null=True)),
                ('faqs_point2', models.TextField(blank=True, null=True)),
                ('faqs_point3', models.TextField(blank=True, null=True)),
                ('faqs_point4', models.TextField(blank=True, null=True)),
                ('faqs_point5', models.TextField(blank=True, null=True)),
                ('faqs_point6', models.TextField(blank=True, null=True)),
                ('faqs_point7', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_user', models.CharField(max_length=256)),
                ('comment_reviewed', models.TextField(blank=True, null=True)),
                ('rating_reviewed', models.FloatField(blank=True, choices=[(1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0)], max_length=5, null=True)),
                ('average_review', models.FloatField(blank=True, max_length=5, null=True)),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tac_heading', models.CharField(blank=True, max_length=128, null=True)),
                ('tac_instance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=64, null=True)),
                ('continent_name', models.CharField(blank=True, max_length=64, null=True)),
                ('country_code', models.CharField(blank=True, max_length=64, null=True)),
                ('country_name', models.CharField(blank=True, max_length=64, null=True)),
                ('dma_code', models.PositiveIntegerField(blank=True, null=True)),
                ('is_in_european_union', models.BooleanField(blank=True, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=8, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=64, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=256)),
                ('property_description', models.CharField(max_length=1024)),
                ('property_about', models.TextField()),
                ('property_rooms', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], null=True)),
                ('property_bathroom', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], null=True)),
                ('property_address', models.CharField(max_length=64)),
                ('property_price', models.CharField(max_length=64)),
                ('property_condition', models.CharField(choices=[('New', 'New'), ('Renovated', 'Renovated'), ('Old', 'Old')], max_length=64)),
                ('property_status', models.CharField(choices=[('For Rent', 'For Rent'), ('For Sale', 'For Sale')], max_length=64)),
                ('property_square_meters', models.CharField(max_length=64)),
                ('property_posted_by', models.CharField(choices=[('Property Owner', 'Property Owner'), ('Property Agent', 'Property Agent'), ('Property Manager', 'Property Manager'), ('Real Estate Company', 'Real Estate Company')], max_length=64)),
                ('property_post_date', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Commercial', 'Commercial'), ('Land', 'Land')], max_length=64)),
                ('property_active', models.BooleanField(default=True)),
                ('property_pic1', models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic2', models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic3', models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic4', models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic5', models.ImageField(blank=True, null=True, upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic6', models.ImageField(blank=True, null=True, upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic7', models.ImageField(blank=True, null=True, upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('property_pic8', models.ImageField(blank=True, null=True, upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image])),
                ('kitchen', models.BooleanField()),
                ('air_condition', models.BooleanField()),
                ('balcony', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('garden', models.BooleanField()),
                ('cctv', models.BooleanField()),
                ('playground', models.BooleanField()),
                ('furnished', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('school', models.BooleanField(blank=True, null=True)),
                ('hospital', models.BooleanField(blank=True, null=True)),
                ('borehole', models.BooleanField(blank=True, null=True)),
                ('bus_stop', models.BooleanField(blank=True, null=True)),
                ('internet_service_provider', models.BooleanField(blank=True, null=True)),
                ('bank', models.BooleanField(blank=True, null=True)),
                ('mall', models.BooleanField(blank=True, null=True)),
                ('shops', models.BooleanField(blank=True, null=True)),
                ('main_road', models.BooleanField(blank=True, null=True)),
                ('property_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to=main.extras.profile_picture)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('registered_as', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.PositiveIntegerField()),
                ('property_viewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.property')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=256)),
                ('article_intro', models.CharField(max_length=512)),
                ('article_post_date', models.DateField(max_length=64)),
                ('article_tag', models.CharField(max_length=64)),
                ('article_picture', models.ImageField(blank=True, null=True, upload_to=main.extras.blog_pictures)),
                ('article_content', models.TextField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
