# Generated by Django 3.2.3 on 2021-05-25 17:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_property_property_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic1',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic3',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic4',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic5',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic6',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic7',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
        migrations.AddField(
            model_name='property',
            name='property_pic8',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_pic_name),
        ),
    ]
