# Generated by Django 3.2.3 on 2021-05-28 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210528_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
