# Generated by Django 3.2.3 on 2021-05-28 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_property_property_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
