# Generated by Django 3.2.3 on 2021-05-28 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_property_property_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
