# Generated by Django 3.2.3 on 2021-05-29 09:26

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210529_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_height',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_width',
            field=models.IntegerField(default='20'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic1',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic2',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic3',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic4',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic5',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic6',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic7',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic8',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='20'), null=True, upload_to=main.models.get_pic_name, validators=[main.models.validate_image], width_field=models.IntegerField(default='20')),
        ),
    ]
