# Generated by Django 3.2.3 on 2021-05-30 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_pageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('continent_code', models.CharField(max_length=64)),
                ('continent_name', models.CharField(max_length=64)),
                ('country_code', models.CharField(max_length=64)),
                ('country_name', models.CharField(max_length=64)),
                ('dma_code', models.PositiveIntegerField()),
                ('is_in_european_union', models.BooleanField()),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
                ('postal_code', models.IntegerField()),
                ('region', models.CharField(max_length=8)),
                ('time_zone', models.CharField(max_length=64)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
