# Generated by Django 3.2.3 on 2021-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_review_reviewed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating_reviewed',
            field=models.FloatField(blank=True, choices=[(1.0, 1.0), (2.0, 2.0), (3.0, 3.0), (4.0, 4.0), (5.0, 5.0)], max_length=5, null=True),
        ),
    ]
