# Generated by Django 3.2.3 on 2021-06-04 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.extras


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_alter_review_rating_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=256)),
                ('article_intro', models.CharField(max_length=512)),
                ('article_post_date', models.CharField(max_length=64)),
                ('article_tag', models.CharField(max_length=64)),
                ('article_picture', models.ImageField(blank=True, null=True, upload_to=main.extras.blog_pictures)),
                ('article_content', models.TextField()),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
