# Generated by Django 3.2.3 on 2021-06-05 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import main.extras


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_alter_article_article_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=main.extras.profile_picture)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(max_length=128)),
                ('registered_as', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Agent'), (3, 'Real Estate Developer'), (4, 'Auctioneer'), (5, 'Client')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
