# Generated by Django 3.2.3 on 2021-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_as',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('ADMIN', 'Admin'), ('AGENT', 'Agent'), ('REAL_ESTATE_DEVELOPER', 'Real Estate Developer'), ('AUCTIONEER', 'Auctioneer'), ('CLIENT', 'Client')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_posted_by',
            field=models.CharField(choices=[('Property Owner', 'Property Owner'), ('Property Agent', 'Property Agent'), ('Property Manager', 'Property Manager'), ('Real Estate Company', 'Real Estate Company')], max_length=64),
        ),
    ]
