# Generated by Django 3.2.3 on 2021-06-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210610_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_as',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Real Estate Developer', 'Real Estate Developer'), ('Auctioneer', 'Auctioneer'), ('Client', 'Client')], null=True),
        ),
    ]
