# Generated by Django 3.2.3 on 2021-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_profile_registered_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_as',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Agent', 'Agent'), ('Real Estate Developer', 'Real Estate Developer'), ('Auctioneer', 'Auctioneer'), ('Client', 'Client')], max_length=32, null=True),
        ),
    ]
