# Generated by Django 3.2.3 on 2021-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_profile_registered_as'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faqs_headline', models.CharField(blank=True, max_length=256, null=True)),
                ('faqs_content', models.TextField()),
            ],
        ),
    ]
