# Generated by Django 3.2.3 on 2021-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='tac_heading',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
