# Generated by Django 3.2.3 on 2021-06-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_termsandconditions_tac_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='faqs_content',
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqs',
            name='faqs_point7',
            field=models.TextField(blank=True, null=True),
        ),
    ]
