# Generated by Django 3.2.3 on 2021-07-03 18:00

from django.db import migrations, models
import main.extras


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_pic1',
            field=models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic2',
            field=models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image]),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_pic3',
            field=models.ImageField(upload_to=main.extras.get_pic_name, validators=[main.extras.validate_image]),
        ),
    ]
