# Generated by Django 3.2.3 on 2021-07-12 13:32

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210703_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
