# Generated by Django 3.2.3 on 2021-07-12 22:07

from django.db import migrations, models
import django_countries.fields
import main.extras


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210712_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='img/default.jpg', upload_to=main.extras.profile_picture),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
