# Generated by Django 3.2.3 on 2021-07-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_auto_20210712_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_as',
            field=models.CharField(blank=True, choices=[('Agent', 'Agent'), ('Real Estate Developer', 'Real Estate Developer'), ('Auctioneer', 'Auctioneer'), ('Client', 'Client')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
