# Generated by Django 3.2.3 on 2021-07-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20210713_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_location',
            field=models.CharField(max_length=64),
        ),
    ]
