# Generated by Django 3.2.3 on 2021-07-26 00:59

from django.db import migrations, models
import main.extras


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210725_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to=main.extras.profile_picture),
        ),
    ]
